# should be in the parent dir of the project on level with client/server folders;
version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ../server
    volumes: [
     "/node_modules",
      "./server:/app"]
  client:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    ports: ["80:80"]